modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
[[mods]]
modId = "minelzu"
version = "${file.jarVersion}"
displayName = "MineLZU"
authors = "WeLanCraft, Tapio"
description = '''
'''